services:
  model:
    image: ghcr.io/sperekrestova/pill-checker-model:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 6G
    networks:
      - private_network

  core:
    image: ghcr.io/sperekrestova/pill-checker-core:latest
    env_file:
      - core.env
    ports:
      - "8000:8000"
    environment:
      BIOMED_HOST: "model:8081"
    restart: always
    networks:
      - private_network

#  ui:
#    image: ghcr.io/sperekrestova/pill-checker-ui:latest
#    ports:
#      - "19000:19000"
#      - "19001:19001"
#      - "19002:19002"
#    restart: always
#    networks:
#      - private_network

networks:
  private_network:
    driver: bridge
