name: Run Tests

on: [push]

jobs:
  test_model:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd BiomedNER
          pip install --no-cache-dir -r requirements.txt
          pip install pytest
          pip install httpx

      - name: Run tests
        run: |
          cd BiomedNER
          python -m unittest tests/test_main.py


  test_service:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd MedsRecognition
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load environment variables
        run: |
          cd MedsRecognition
          echo "DJANGO_SETTINGS_MODULE=MedsRecognition.settings" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd MedsRecognition
          python manage.py test
